osx_image: xcode7.3
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage update --platform iOS,Mac

script:
- xctool clean build -project OhMyAuth.xcodeproj -scheme OhMyAuth-iOS -sdk iphonesimulator
- xctool test -project OhMyAuth.xcodeproj -scheme OhMyAuth-iOS -sdk iphonesimulator
- xctool clean build -project OhMyAuth.xcodeproj -scheme OhMyAuth-Mac -sdk macosx
- xctool test -project OhMyAuth.xcodeproj -scheme OhMyAuth-Mac -sdk macosx
